import type { JSX } from 'react';

import { breadcrumbSchema, webPageSchema } from '@vijayhardaha/schema-builder';
import { JsonLd } from '@vijayhardaha/schema-builder/react';
import type { Metadata } from 'next';

import { PageContent } from '@/components/page/PageContent';
import { PageHeader } from '@/components/page/PageHeader';
import { PageLayout } from '@/components/page/PageLayout';
import { buildMetadata } from '@/utils/meta';
import { globalSchema, buildBreadcrumbs } from '@/utils/schema';
import { siteUrl, getSeoByPath } from '@/utils/seo';

const rootUrl = siteUrl();
const { seoTitle, seoDescription, path: seoPath } = getSeoByPath('/terms-conditions')!;

const schemaData = [
  ...globalSchema(),
  webPageSchema({ rootUrl, path: seoPath, breadcrumb: true }, { name: seoTitle, description: seoDescription }),
  breadcrumbSchema({ rootUrl, items: buildBreadcrumbs(seoPath, 'Terms & Conditions') }),
];

/**
 * SEO metadata for the Terms & Conditions page.
 *
 * @type {Metadata}
 */
export const metadata: Metadata = buildMetadata({ seoTitle, seoDescription, path: seoPath });

/**
 * Terms and Conditions page component.
 * Provides detailed information about the terms of service for using the platform.
 *
 * @returns {JSX.Element} The rendered Terms and Conditions page.
 */
export default function TermsConditions(): JSX.Element {
  return (
    <>
      <JsonLd data={schemaData} />
      <PageLayout>
        <PageHeader
          pageName="Terms & Conditions"
          title="Terms and Conditions"
          description="Please read these terms carefully before using our free online tools and services."
        />
        <PageContent>
          <div className="space-y-6 text-base leading-relaxed text-gray-800">
            <p>
              <strong>Last updated:</strong> June 16, 2026
            </p>

            <h2 className="text-xl font-bold text-gray-900">1. Acceptance of Terms</h2>

            <p>
              By accessing or using <strong>Tools by Vijay</strong> (&quot;the Website&quot;), you agree to be bound by
              these Terms and Conditions (&quot;Terms&quot;). If you do not agree with any part of these Terms, you must
              not access or use the Website.
            </p>

            <p>
              These Terms apply to all visitors, users, and others who access or use any of the tools and services
              available on the Website.
            </p>

            <h2 className="text-xl font-bold text-gray-900">2. Description of Service</h2>

            <p>
              Tools by Vijay provides a collection of free online utilities and tools designed for developers, content
              creators, and general users. These include, but are not limited to:
            </p>

            <ul className="list-disc space-y-1 pl-6">
              <li>Text transformation tools (slug generators, case changers, text-to-array converters)</li>
              <li>Code optimization tools (HTML/CSS/JS minifiers, code beautifiers, CSS inliners)</li>
              <li>Security tools (password generators, password strength checkers)</li>
              <li>Data conversion tools (Base64 encoder/decoder, JSON sorters, quote replacers)</li>
              <li>Generation tools (QR codes, barcodes, random usernames, country names)</li>
              <li>URL utilities (URL encoders/decoders, URL shorteners)</li>
              <li>Content organization tools (duplicate line removers, line sorters, shuffle tools)</li>
            </ul>

            <p>
              All tools are provided <strong>free of charge</strong>. There are no paid tiers, subscription plans, or
              premium features.
            </p>

            <h2 className="text-xl font-bold text-gray-900">3. User Responsibilities</h2>

            <p>By using the Website, you agree to the following:</p>

            <ul className="list-disc space-y-1 pl-6">
              <li>
                You will <strong>not</strong> use the tools for any unlawful purpose or in violation of any applicable
                laws or regulations.
              </li>
              <li>
                You will <strong>not</strong> attempt to disrupt, overload, or compromise the Website&apos;s
                infrastructure or security.
              </li>
              <li>
                You will <strong>not</strong> use automated scripts, bots, or scrapers to access the tools or APIs in a
                manner that could impair the service for other users.
              </li>
              <li>
                You will <strong>not</strong> submit any content through the tools that is illegal, harmful,
                threatening, abusive, defamatory, or otherwise objectionable.
              </li>
              <li>
                You are solely responsible for any data you input into the tools and how you use the output generated by
                the tools.
              </li>
            </ul>

            <h2 className="text-xl font-bold text-gray-900">4. Intellectual Property</h2>

            <h3 className="text-lg font-semibold text-gray-900">Website Content</h3>

            <p>
              The Website, including its design, layout, text, graphics, and code (excluding open-source libraries), is
              the intellectual property of <strong>Vijay Hardaha</strong> and is protected by applicable copyright laws.
            </p>

            <h3 className="text-lg font-semibold text-gray-900">Open-Source Components</h3>

            <p>
              This Website incorporates several open-source libraries that are used under their respective licenses. Key
              libraries include:
            </p>

            <ul className="list-disc space-y-1 pl-6">
              <li>
                <strong>Next.js</strong> (MIT License) — React framework for the frontend and API routes
              </li>
              <li>
                <strong>Tailwind CSS</strong> (MIT License) — Utility-first CSS framework
              </li>
              <li>
                <strong>@putout/minify</strong> (MIT License) — JavaScript minification
              </li>
              <li>
                <strong>clean-css</strong> (MIT License) — CSS minification
              </li>
              <li>
                <strong>html-minifier-terser</strong> (MIT License) — HTML minification
              </li>
              <li>
                <strong>juice</strong> (MIT License) — CSS inlining
              </li>
              <li>
                <strong>Prettier</strong> (MIT License) — Code formatting and beautification
              </li>
              <li>
                <strong>slugify</strong> (MIT License) — URL slug generation
              </li>
              <li>
                <strong>react-icons</strong> (MIT License) — Icon library
              </li>
            </ul>

            <p>
              The source code for this website is publicly available on{' '}
              <a
                href="https://github.com/vijayhardaha/tools-by-vijay"
                className="font-medium text-pink-500 underline hover:no-underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                GitHub
              </a>{' '}
              and may be viewed, forked, and contributed to under the terms of the license specified in the repository.
            </p>

            <h2 className="text-xl font-bold text-gray-900">5. Disclaimer of Warranties</h2>

            <p>
              The tools and services on this Website are provided on an <strong>&quot;as is&quot;</strong> and{' '}
              <strong>&quot;as available&quot;</strong> basis without any warranties of any kind, either express or
              implied.
            </p>

            <p>
              We do <strong>not</strong> guarantee that:
            </p>

            <ul className="list-disc space-y-1 pl-6">
              <li>The tools will be uninterrupted, timely, secure, or error-free.</li>
              <li>
                The results obtained from using the tools will be accurate, complete, or reliable for your specific use
                case.
              </li>
              <li>Any errors or defects in the software will be corrected.</li>
            </ul>

            <p>
              You acknowledge that the tools are provided as general-purpose utilities and should not be relied upon as
              the sole basis for critical decisions, security-sensitive applications, or production environments without
              independent verification.
            </p>

            <h2 className="text-xl font-bold text-gray-900">6. Limitation of Liability</h2>

            <p>
              To the fullest extent permitted by applicable law, <strong>Vijay Hardaha</strong> and the Website shall
              not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not
              limited to:
            </p>

            <ul className="list-disc space-y-1 pl-6">
              <li>Loss of data, profits, or business opportunities</li>
              <li>Service interruption or computer damage</li>
              <li>Claims arising from the use or inability to use the tools</li>
              <li>Errors or omissions in tool outputs that result in financial or reputational harm</li>
            </ul>

            <p>
              Our total liability for any claim arising from your use of the Website shall not exceed the amount you
              have paid us in the twelve (12) months preceding the claim. Since all tools are free, this amount is zero.
            </p>

            <h2 className="text-xl font-bold text-gray-900">7. Third-Party Services</h2>

            <p>The Website uses the following third-party services which have their own terms and privacy policies:</p>

            <ul className="list-disc space-y-1 pl-6">
              <li>
                <strong>Vercel Inc.</strong> — Hosting provider. Data is processed in accordance with Vercel&apos;s
                Terms of Service and Privacy Policy.
              </li>
              <li>
                <strong>Google Analytics</strong> — Web analytics service. Use is subject to Google&apos;s Terms of
                Service.
              </li>
              <li>
                <strong>GitHub</strong> — Source code hosting. The repository is public and subject to GitHub&apos;s
                Terms of Service.
              </li>
            </ul>

            <p>
              We are not responsible for the content, privacy practices, or terms of these third-party services. Your
              interactions with them are governed by their respective policies.
            </p>

            <h2 className="text-xl font-bold text-gray-900">8. API Usage</h2>

            <p>
              The Website provides certain API endpoints (at <code>/api/*</code>) that power the server-side tools. By
              using these APIs, you agree to:
            </p>

            <ul className="list-disc space-y-1 pl-6">
              <li>Respect the automated origin/referer validation checks that protect against unauthorized access.</li>
              <li>Abide by the 2MB request body size limit.</li>
              <li>Refrain from sending excessive requests that could degrade service availability for other users.</li>
            </ul>

            <p>
              These APIs are intended for use through the Website interface only. Bulk or automated access is not
              permitted without prior written consent.
            </p>

            <h2 className="text-xl font-bold text-gray-900">9. Links to Other Websites</h2>

            <p>
              The Website may contain links to third-party websites or services that are not owned or controlled by us.
              We have no control over, and assume no responsibility for, the content, privacy policies, or practices of
              any third-party websites. You acknowledge and agree that we shall not be liable for any damage or loss
              caused by or in connection with the use of such third-party websites.
            </p>

            <h2 className="text-xl font-bold text-gray-900">10. Changes to Terms</h2>

            <p>
              We reserve the right to modify or replace these Terms at any time. Material changes will be posted on this
              page with an updated &quot;Last updated&quot; date. Your continued use of the Website after any changes
              constitutes acceptance of the new Terms.
            </p>

            <p>
              We encourage you to review these Terms periodically for any updates. If you do not agree to the modified
              Terms, you must discontinue use of the Website.
            </p>

            <h2 className="text-xl font-bold text-gray-900">11. Governing Law</h2>

            <p>
              These Terms shall be governed and construed in accordance with the laws of India, without regard to its
              conflict of law provisions. Any disputes arising from these Terms shall be resolved in the courts of
              India.
            </p>

            <h2 className="text-xl font-bold text-gray-900">12. Contact Information</h2>

            <p>If you have any questions, concerns, or requests regarding these Terms, please reach out:</p>

            <ul className="list-disc space-y-1 pl-6">
              <li>
                Twitter / X:{' '}
                <a
                  href="https://x.com/vijayhardaha"
                  className="font-medium text-pink-500 underline hover:no-underline"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  @vijayhardaha
                </a>
              </li>
              <li>
                GitHub:{' '}
                <a
                  href="https://github.com/vijayhardaha"
                  className="font-medium text-pink-500 underline hover:no-underline"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  github.com/vijayhardaha
                </a>
              </li>
              <li>
                Contact page:{' '}
                <a href="/contact" className="font-medium text-pink-500 underline hover:no-underline">
                  toolsbyvijay.vercel.app/contact
                </a>
              </li>
            </ul>

            <p>
              This website is maintained by <strong>Vijay Hardaha</strong>, an independent web developer based in India.
            </p>
          </div>
        </PageContent>
      </PageLayout>
    </>
  );
}
